### ISSUE TITLE
Minecraft Fabric Egg Giving Error On Clean Install

### ISSUE THREAD

**Issue by JDsWebService** [parkervcp/eggs#1201]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

^ Note: Couldn't find the discord server link. Maybe link it inside the template that auto generates for a more helpful workflow?

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 1.4.2
Daemon Version: Whatever the most current is with 1.4.2. Just installed a fresh ptero 2 days ago.
Service: Minecraft
Modified: Did not change anything.

Expected Behavior:

The server should start up.

Actual Behavior:

Getting this error:
```
container@pterodactyl~ java -Xms128M -Xmx4096M -jar fabric-server-launch.jar
[17:12:26] [main/INFO]: Loading for game Minecraft 1.17
[17:12:27] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'Minecraft' (minecraft) requires version 16 or later of mod 'Eclipse OpenJ9 VM' (java), but a non-matching version is present: 11!
         - You must install version 16 or later of 'Eclipse OpenJ9 VM' (java).
         - Mod 'Eclipse OpenJ9 VM' (java) v11 is being loaded from the user's mod directory.
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

Steps to Reproduce: (Step by step what to do to cause the issue)

1. Fresh install of ptero 1.4.2
2. Import Fabric Egg
3. Allocate two ports on node
4. Create server, allocate those ports.
5. Let it install
6. Installation will say it completed successfully, however when you hit "Start", it will try and start the server and then error out.

**Comment by JDsWebService** [comment]
You can close this issue, as I didn't select the right Java version. Sorry for the confusion.
