### ISSUE TITLE
[Bug]: Space Engineers 

### ISSUE THREAD

**Issue by skynett81** [parkervcp/eggs#1302]
### Panel Version

latest

### Wings Version

latest

### Service

Space Engineers

### Modified

No, I did not modify the egg

### Expected Behavior

i have just ctreated a server , but it wont start

### Actual Behavior

wont run at it should

### Steps To Reproduce

new server vanilla

### Relevant log output

```shell
2021-08-18 03:15:38.212 - Thread:   1 ->  Log Started
2021-08-18 03:15:38.213 - Thread:   1 ->  Timezone (local - UTC): 2h
2021-08-18 03:15:38.213 - Thread:   1 ->  App Version: 01_199_023
2021-08-18 03:15:38.230 - Thread:   1 ->  Is official: True [NO][NIS][NAMP]
2021-08-18 03:15:38.232 - Thread:   1 ->  Branch / Sandbox: DedicatedServer
2021-08-18 03:15:38.233 - Thread:   1 ->  Environment.ProcessorCount: 16
2021-08-18 03:15:38.239 - Thread:   1 ->  Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)
2021-08-18 03:15:38.239 - Thread:   1 ->  Environment.CommandLine: "Z:\home\container\spaceengineers\DedicatedServer64\SpaceEngineersDedicated.exe" -path Z:\home\container\config -noconsole -ignorelastsession
2021-08-18 03:15:38.240 - Thread:   1 ->  Environment.Is64BitProcess: True
2021-08-18 03:15:38.240 - Thread:   1 ->  Environment.Is64BitOperatingSystem: True
2021-08-18 03:15:38.241 - Thread:   1 ->  Environment.Version: .NET Framework 4.8.3761.0
2021-08-18 03:15:38.242 - Thread:   1 ->  Environment.CurrentDirectory: Z:\home\container\spaceengineers\DedicatedServer64
2021-08-18 03:15:38.242 - Thread:   1 ->  CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
2021-08-18 03:15:38.243 - Thread:   1 ->  IntPtr.Size: 8
2021-08-18 03:15:38.243 - Thread:   1 ->  Default Culture: 
2021-08-18 03:15:38.243 - Thread:   1 ->  Default UI Culture: 
2021-08-18 03:15:38.455 - Thread:   1 ->  MyScreenManager()
2021-08-18 03:15:38.634 - Thread:   1 ->  MySandboxGame.Constructor() - START
2021-08-18 03:15:38.638 - Thread:   1 ->     Game dir: Z:\home\container\spaceengineers\DedicatedServer64
2021-08-18 03:15:38.638 - Thread:   1 ->     Content dir: Z:\home\container\spaceengineers\Content
2021-08-18 03:15:47.476 - Thread:   1 ->     Preallocate - START
2021-08-18 03:15:47.482 - Thread:   1 ->        MySpaceWorldGenerator - START
2021-08-18 03:15:47.506 - Thread:   1 ->        MySpaceWorldGenerator - END
2021-08-18 03:15:47.508 - Thread:   1 ->        MySpaceBuildComponent - START
2021-08-18 03:15:47.508 - Thread:   1 ->        MySpaceBuildComponent - END
2021-08-18 03:15:47.509 - Thread:   1 ->        MyEntities - START
2021-08-18 03:15:48.113 - Thread:   1 ->        MyEntities - END
2021-08-18 03:15:48.113 - Thread:   1 ->        MyObjectBuilder_Base - START
2021-08-18 03:15:48.113 - Thread:   1 ->        MyObjectBuilder_Base - END
2021-08-18 03:15:48.114 - Thread:   1 ->        MyTransparentGeometry - START
2021-08-18 03:15:48.130 - Thread:   1 ->        MyTransparentGeometry - END
2021-08-18 03:15:48.130 - Thread:   1 ->        MyCubeGridDeformationTables - START
2021-08-18 03:15:48.160 - Thread:   1 ->        MyCubeGridDeformationTables - END
2021-08-18 03:15:48.160 - Thread:   1 ->        MyMath - START
2021-08-18 03:15:48.161 - Thread:   1 ->        MyMath - END
2021-08-18 03:15:48.161 - Thread:   1 ->        MySimpleObjectDraw - START
2021-08-18 03:15:48.161 - Thread:   1 ->        MySimpleObjectDraw - END
2021-08-18 03:15:48.246 - Thread:   1 ->        MyEntityComponentsDebugDraw - START
2021-08-18 03:15:48.246 - Thread:   1 ->        MyEntityComponentsDebugDraw - END
2021-08-18 03:15:48.246 - Thread:   1 ->        MyGuiIngameScriptsPage - START
2021-08-18 03:15:48.627 - Thread:   1 ->        MyGuiIngameScriptsPage - END
2021-08-18 03:15:48.644 - Thread:   1 ->        MyGuiScreenAdminMenu - START
2021-08-18 03:15:48.646 - Thread:   1 ->        MyGuiScreenAdminMenu - END
2021-08-18 03:15:48.646 - Thread:   1 ->        MySyncDestructions - START
2021-08-18 03:15:48.646 - Thread:   1 ->        MySyncDestructions - END
2021-08-18 03:15:48.646 - Thread:   1 ->        MySyncEntity - START
2021-08-18 03:15:48.646 - Thread:   1 ->        MySyncEntity - END
2021-08-18 03:15:48.646 - Thread:   1 ->        MyCommandCharacter - START
2021-08-18 03:15:48.652 - Thread:   1 ->        MyCommandCharacter - END
2021-08-18 03:15:48.652 - Thread:   1 ->        MyCommandConsole - START
2021-08-18 03:15:48.655 - Thread:   1 ->        MyCommandConsole - END
2021-08-18 03:15:48.656 - Thread:   1 ->        MyCommandEntity - START
2021-08-18 03:15:48.660 - Thread:   1 ->        MyCommandEntity - END
2021-08-18 03:15:48.660 - Thread:   1 ->        MyAiTargetManager - START
2021-08-18 03:15:48.660 - Thread:   1 ->        MyAiTargetManager - END
2021-08-18 03:15:48.660 - Thread:   1 ->        MyClientDebugCommands - START
2021-08-18 03:15:48.664 - Thread:   1 ->        MyClientDebugCommands - END
2021-08-18 03:15:48.664 - Thread:   1 ->        MyDedicatedServer - START
2021-08-18 03:15:48.664 - Thread:   1 ->        MyDedicatedServer - END
2021-08-18 03:15:48.664 - Thread:   1 ->        MyDedicatedServerBase - START
2021-08-18 03:15:48.664 - Thread:   1 ->        MyDedicatedServerBase - END
2021-08-18 03:15:48.664 - Thread:   1 ->        MyMultiplayerBase - START
2021-08-18 03:15:48.664 - Thread:   1 ->        MyMultiplayerBase - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerClient - START
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerClient - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerClientBase - START
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerClientBase - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerLobby - START
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerLobby - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerLobbyClient - START
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerLobbyClient - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerServerBase - START
2021-08-18 03:15:48.665 - Thread:   1 ->        MyMultiplayerServerBase - END
2021-08-18 03:15:48.665 - Thread:   1 ->        MyServerDebugCommands - START
2021-08-18 03:15:48.671 - Thread:   1 ->        MyServerDebugCommands - END
2021-08-18 03:15:48.671 - Thread:   1 ->        MyAIActionsParser - START
2021-08-18 03:15:48.672 - Thread:   1 ->        MyAIActionsParser - END
2021-08-18 03:15:48.673 - Thread:   1 ->        MyCubeGridDefinitions - START
2021-08-18 03:15:48.886 - Thread:   1 ->        MyCubeGridDefinitions - END
2021-08-18 03:15:48.886 - Thread:   1 ->        MyDefinitionManager - START
2021-08-18 03:15:48.956 - Thread:   1 ->        MyDefinitionManager - END
2021-08-18 03:15:48.962 - Thread:   1 ->     Preallocate - END
2021-08-18 03:15:48.978 - Thread:   1 ->     Bind IP : 0.0.0.0:27016
2021-08-18 03:15:59.656 - Thread:   1 ->     Error binding server endpoint: Unknown error (0x2726)
2021-08-18 03:15:59.723 - Thread:   1 ->     Exception occurred: System.Exception: Fatal error during dedicated server init see log for more information.
   at Sandbox.MySandboxGame..ctor(String[] commandlineArgs, IntPtr windowHandle)
   at VRage.Dedicated.DedicatedServer.NewGame()
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2021-08-18 03:15:59.723 - Thread:   1 ->     Exception Data:
	Silent: True
2021-08-18 03:15:59.727 - Thread:   1 ->     Showing message
2021-08-18 03:16:31.309 - Thread:   1 ->     Log Closed
```

**Comment by gOOvER** [comment]
Start can Take a Long Time. so you need to wait

**Comment by skynett81** [comment]
i know , but only goes in loops and restarts  . so something is wrong somewhere

**Comment by gOOvER** [comment]
i dont see any loop or restart in your logs

Start can take 15 mins

**Comment by skynett81** [comment]
2021-08-18 18:42:03.840 - Thread:   1 ->  Log Started
2021-08-18 18:42:03.843 - Thread:   1 ->  Timezone (local - UTC): 2h
2021-08-18 18:42:03.843 - Thread:   1 ->  App Version: 01_199_023
2021-08-18 18:42:03.861 - Thread:   1 ->  Is official: True [NO][NIS][NAMP]
2021-08-18 18:42:03.864 - Thread:   1 ->  Branch / Sandbox: DedicatedServer
2021-08-18 18:42:03.864 - Thread:   1 ->  Environment.ProcessorCount: 16
2021-08-18 18:42:03.869 - Thread:   1 ->  Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)
2021-08-18 18:42:03.870 - Thread:   1 ->  Environment.CommandLine: "Z:\home\container\spaceengineers\DedicatedServer64\SpaceEngineersDedicated.exe" -path Z:\home\container\config -noconsole -ignorelastsession
2021-08-18 18:42:03.870 - Thread:   1 ->  Environment.Is64BitProcess: True
2021-08-18 18:42:03.871 - Thread:   1 ->  Environment.Is64BitOperatingSystem: True
2021-08-18 18:42:03.873 - Thread:   1 ->  Environment.Version: .NET Framework 4.8.3761.0
2021-08-18 18:42:03.874 - Thread:   1 ->  Environment.CurrentDirectory: Z:\home\container\spaceengineers\DedicatedServer64
2021-08-18 18:42:03.877 - Thread:   1 ->  CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
2021-08-18 18:42:03.877 - Thread:   1 ->  IntPtr.Size: 8
2021-08-18 18:42:03.877 - Thread:   1 ->  Default Culture: 
2021-08-18 18:42:03.877 - Thread:   1 ->  Default UI Culture: 
2021-08-18 18:42:04.133 - Thread:   1 ->  MyScreenManager()
2021-08-18 18:42:04.331 - Thread:   1 ->  MySandboxGame.Constructor() - START
2021-08-18 18:42:04.335 - Thread:   1 ->     Game dir: Z:\home\container\spaceengineers\DedicatedServer64
2021-08-18 18:42:04.335 - Thread:   1 ->     Content dir: Z:\home\container\spaceengineers\Content
2021-08-18 18:42:14.324 - Thread:   1 ->     Preallocate - START
2021-08-18 18:42:14.330 - Thread:   1 ->        MySpaceWorldGenerator - START
2021-08-18 18:42:14.361 - Thread:   1 ->        MySpaceWorldGenerator - END
2021-08-18 18:42:14.363 - Thread:   1 ->        MySpaceBuildComponent - START
2021-08-18 18:42:14.363 - Thread:   1 ->        MySpaceBuildComponent - END
2021-08-18 18:42:14.366 - Thread:   1 ->        MyEntities - START
2021-08-18 18:42:15.068 - Thread:   1 ->        MyEntities - END
2021-08-18 18:42:15.068 - Thread:   1 ->        MyObjectBuilder_Base - START
2021-08-18 18:42:15.068 - Thread:   1 ->        MyObjectBuilder_Base - END
2021-08-18 18:42:15.069 - Thread:   1 ->        MyTransparentGeometry - START
2021-08-18 18:42:15.069 - Thread:   1 ->        MyTransparentGeometry - END
2021-08-18 18:42:15.069 - Thread:   1 ->        MyCubeGridDeformationTables - START
2021-08-18 18:42:15.126 - Thread:   1 ->        MyCubeGridDeformationTables - END
2021-08-18 18:42:15.126 - Thread:   1 ->        MyMath - START
2021-08-18 18:42:15.126 - Thread:   1 ->        MyMath - END
2021-08-18 18:42:15.127 - Thread:   1 ->        MySimpleObjectDraw - START
2021-08-18 18:42:15.127 - Thread:   1 ->        MySimpleObjectDraw - END
2021-08-18 18:42:15.289 - Thread:   1 ->        MyEntityComponentsDebugDraw - START
2021-08-18 18:42:15.289 - Thread:   1 ->        MyEntityComponentsDebugDraw - END
2021-08-18 18:42:15.289 - Thread:   1 ->        MyGuiIngameScriptsPage - START
2021-08-18 18:42:15.768 - Thread:   1 ->        MyGuiIngameScriptsPage - END
2021-08-18 18:42:15.770 - Thread:   1 ->        MyGuiScreenAdminMenu - START
2021-08-18 18:42:15.772 - Thread:   1 ->        MyGuiScreenAdminMenu - END
2021-08-18 18:42:15.773 - Thread:   1 ->        MySyncDestructions - START
2021-08-18 18:42:15.773 - Thread:   1 ->        MySyncDestructions - END
2021-08-18 18:42:15.773 - Thread:   1 ->        MySyncEntity - START
2021-08-18 18:42:15.773 - Thread:   1 ->        MySyncEntity - END
2021-08-18 18:42:15.773 - Thread:   1 ->        MyCommandCharacter - START
2021-08-18 18:42:15.780 - Thread:   1 ->        MyCommandCharacter - END
2021-08-18 18:42:15.780 - Thread:   1 ->        MyCommandConsole - START
2021-08-18 18:42:15.783 - Thread:   1 ->        MyCommandConsole - END
2021-08-18 18:42:15.783 - Thread:   1 ->        MyCommandEntity - START
2021-08-18 18:42:15.790 - Thread:   1 ->        MyCommandEntity - END
2021-08-18 18:42:15.790 - Thread:   1 ->        MyAiTargetManager - START
2021-08-18 18:42:15.790 - Thread:   1 ->        MyAiTargetManager - END
2021-08-18 18:42:15.790 - Thread:   1 ->        MyClientDebugCommands - START
2021-08-18 18:42:15.795 - Thread:   1 ->        MyClientDebugCommands - END
2021-08-18 18:42:15.795 - Thread:   1 ->        MyDedicatedServer - START
2021-08-18 18:42:15.795 - Thread:   1 ->        MyDedicatedServer - END
2021-08-18 18:42:15.795 - Thread:   1 ->        MyDedicatedServerBase - START
2021-08-18 18:42:15.795 - Thread:   1 ->        MyDedicatedServerBase - END
2021-08-18 18:42:15.795 - Thread:   1 ->        MyMultiplayerBase - START
2021-08-18 18:42:15.795 - Thread:   1 ->        MyMultiplayerBase - END
2021-08-18 18:42:15.795 - Thread:   1 ->        MyMultiplayerClient - START
2021-08-18 18:42:15.795 - Thread:   1 ->        MyMultiplayerClient - END
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerClientBase - START
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerClientBase - END
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerLobby - START
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerLobby - END
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerLobbyClient - START
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerLobbyClient - END
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerServerBase - START
2021-08-18 18:42:15.796 - Thread:   1 ->        MyMultiplayerServerBase - END
2021-08-18 18:42:15.796 - Thread:   1 ->        MyServerDebugCommands - START
2021-08-18 18:42:15.802 - Thread:   1 ->        MyServerDebugCommands - END
2021-08-18 18:42:15.802 - Thread:   1 ->        MyAIActionsParser - START
2021-08-18 18:42:15.804 - Thread:   1 ->        MyAIActionsParser - END
2021-08-18 18:42:15.804 - Thread:   1 ->        MyCubeGridDefinitions - START
2021-08-18 18:42:16.098 - Thread:   1 ->        MyCubeGridDefinitions - END
2021-08-18 18:42:16.098 - Thread:   1 ->        MyDefinitionManager - START
2021-08-18 18:42:16.179 - Thread:   1 ->        MyDefinitionManager - END
2021-08-18 18:42:16.185 - Thread:   1 ->     Preallocate - END
2021-08-18 18:42:16.203 - Thread:   1 ->     Bind IP : 91.134.14.152:27016
2021-08-18 18:42:28.489 - Thread:   1 ->     Error binding server endpoint: Unknown error (0x2726)
2021-08-18 18:42:28.572 - Thread:   1 ->     Exception occurred: System.Exception: Fatal error during dedicated server init see log for more information.
   at Sandbox.MySandboxGame..ctor(String[] commandlineArgs, IntPtr windowHandle)
   at VRage.Dedicated.DedicatedServer.NewGame()
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args, Action`1 initializeServices)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2021-08-18 18:42:28.572 - Thread:   1 ->     Exception Data:
	Silent: True
2021-08-18 18:42:28.578 - Thread:   1 ->     Showing message
2021-08-18 18:43:05.309 - Thread:   1 ->     Log Closed

**Comment by skynett81** [comment]
and i got a new file every time it restarts .... new log

**Comment by Software-Noob** [comment]
You are trying to bind machine IP when instead it should be 0.0.0.0 with allocation determining the IP of the server. Change the config back to default and retry

**Comment by skynett81** [comment]
> You are trying to bind machine IP when instead it should be 0.0.0.0 with allocation determining the IP of the server. Change the config back to default and retry

i have also tested that and same results in reboots

**Comment by skynett81** [comment]
this happens when i use 0.0.0.0


[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:90485be496339b1796a724923be06d4853fc0a934786131e48ea52da1e4303cf 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_wine-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

No appid set. Starting Server
First launch will throw some errors. Ignore them
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
:/home/container$ cd /home/container/spaceengineers/DedicatedServer64/; wine /home/container/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
2021-08-18 18:57:30.848: App Version: 01_199_023
2021-08-18 18:57:30.868: Is official: True [NO][NIS][NAMP]
2021-08-18 18:57:30.870: Environment.ProcessorCount: 16
2021-08-18 18:57:30.877: Environment.OSVersion: Microsoft Windows 7 Professional
 (Microsoft Windows NT 6.1.7601 Service Pack 1)
2021-08-18 18:57:30.878: Environment.CommandLine: "Z:\home\container\spaceengine
ers\DedicatedServer64\SpaceEngineersDedicated.exe" -path Z:\home\container\confi
g -noconsole -ignorelastsession
2021-08-18 18:57:30.878: Environment.Is64BitProcess: True
2021-08-18 18:57:30.878: Environment.Is64BitOperatingSystem: True
2021-08-18 18:57:30.880: Environment.Version: .NET Framework 4.8.3761.0
2021-08-18 18:57:30.880: Environment.CurrentDirectory: Z:\home\container\spaceen
gineers\DedicatedServer64
2021-08-18 18:57:30.881: CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Computer does not meet minimum requirements, forcing Experimental mode
2021-08-18 18:57:42.418: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
dbus[47]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F86D41DA7BB (thread 0060), starting debugger...
wine client error:5c: write: Bad file descriptor
2021-08-18 18:57:55.226: Networking service: Steam
2021-08-18 18:57:55.227: Server successfully started
2021-08-18 18:57:55.227: Product name: Space Engineers
2021-08-18 18:57:55.228: Desc: Space Engineers
2021-08-18 18:57:55.229: Public IP: 91.134.14.152
2021-08-18 18:57:55.230: User ID: [009...224]
2021-08-18 18:57:55.236: Server connected to Steam
2021-08-18 18:57:55.237: Server PolicyResponse (1)
2021-08-18 18:57:56.391: Server Name: GeekLan Space Engineer Server
2021-08-18 18:57:56.392: World Name: Geeklan
2021-08-18 18:57:56.514: Auto Restart Enabled
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:90485be496339b1796a724923be06d4853fc0a934786131e48ea52da1e4303cf 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_wine-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

No appid set. Starting Server
First launch will throw some errors. Ignore them
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
:/home/container$ cd /home/container/spaceengineers/DedicatedServer64/; wine /home/container/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
2021-08-18 18:58:09.120: App Version: 01_199_023
2021-08-18 18:58:09.137: Is official: True [NO][NIS][NAMP]
2021-08-18 18:58:09.139: Environment.ProcessorCount: 16
2021-08-18 18:58:09.146: Environment.OSVersion: Microsoft Windows 7 Professional
 (Microsoft Windows NT 6.1.7601 Service Pack 1)
2021-08-18 18:58:09.147: Environment.CommandLine: "Z:\home\container\spaceengine
ers\DedicatedServer64\SpaceEngineersDedicated.exe" -path Z:\home\container\confi
g -noconsole -ignorelastsession
2021-08-18 18:58:09.147: Environment.Is64BitProcess: True
2021-08-18 18:58:09.148: Environment.Is64BitOperatingSystem: True
2021-08-18 18:58:09.149: Environment.Version: .NET Framework 4.8.3761.0
2021-08-18 18:58:09.152: Environment.CurrentDirectory: Z:\home\container\spaceen
gineers\DedicatedServer64
2021-08-18 18:58:09.152: CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Computer does not meet minimum requirements, forcing Experimental mode
2021-08-18 18:58:21.029: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
dbus[48]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007FF38AC3A7BB (thread 0060), starting debugger...
wine client error:154: write: Bad file descriptor
2021-08-18 18:58:43.132: Error: No IP assigned.
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:90485be496339b1796a724923be06d4853fc0a934786131e48ea52da1e4303cf 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:debian_wine-5 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.8
Current timezone: Etc/UTC
wine-6.0
steam user is not set.

Using anonymous user.

No appid set. Starting Server
First launch will throw some errors. Ignore them
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
:/home/container$ cd /home/container/spaceengineers/DedicatedServer64/; wine /home/container/spaceengineers/DedicatedServer64/SpaceEngineersDedicated.exe -path Z:\\home\\container\\config -noconsole -ignorelastsession
2021-08-18 19:00:13.153: App Version: 01_199_023
2021-08-18 19:00:13.176: Is official: True [NO][NIS][NAMP]
2021-08-18 19:00:13.180: Environment.ProcessorCount: 16
2021-08-18 19:00:13.187: Environment.OSVersion: Microsoft Windows 7 Professional
 (Microsoft Windows NT 6.1.7601 Service Pack 1)
2021-08-18 19:00:13.188: Environment.CommandLine: "Z:\home\container\spaceengine
ers\DedicatedServer64\SpaceEngineersDedicated.exe" -path Z:\home\container\confi
g -noconsole -ignorelastsession
2021-08-18 19:00:13.188: Environment.Is64BitProcess: True
2021-08-18 19:00:13.189: Environment.Is64BitOperatingSystem: True
2021-08-18 19:00:13.193: Environment.Version: .NET Framework 4.8.3761.0
2021-08-18 19:00:13.194: Environment.CurrentDirectory: Z:\home\container\spaceen
gineers\DedicatedServer64
2021-08-18 19:00:13.195: CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Computer does not meet minimum requirements, forcing Experimental mode
2021-08-18 19:00:25.149: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
dbus[48]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F6B7364C7BB (thread 0060), starting debugger...
wine client error:154: write: Bad file descriptor
2021-08-18 19:00:38.645: Networking service: Steam
2021-08-18 19:00:38.646: Server successfully started
2021-08-18 19:00:38.646: Product name: Space Engineers
2021-08-18 19:00:38.650: Desc: Space Engineers
2021-08-18 19:00:38.650: Public IP: 91.134.14.152
2021-08-18 19:00:38.651: User ID: [009...248]
2021-08-18 19:00:38.658: Server connected to Steam
2021-08-18 19:00:38.658: Server PolicyResponse (1)
2021-08-18 19:00:39.698: Server Name: GeekLan Space Engineer Server
2021-08-18 19:00:39.698: World Name: Geeklan
2021-08-18 19:00:39.846: Auto Restart Enabled
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by gOOvER** [comment]
how many ram did you allocated?

**Comment by gOOvER** [comment]
as i know you need 16GB for it

**Comment by skynett81** [comment]
it has unlimited ... whys that ?

**Comment by gOOvER** [comment]
wwwww

> it has unlimited ... whys that ?

Useless answer. How many ram have you Server

**Comment by skynett81** [comment]
64GB

**Comment by gOOvER** [comment]
Here's your error:

```
2021-08-18 19:00:13.195: CPU Info: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Computer does not meet minimum requirements, forcing Experimental mode
```

**Comment by gOOvER** [comment]
Really old CPU

**Comment by skynett81** [comment]
yea i did thinking it maybe was that . 

but thx for the bug helping

**Comment by gOOvER** [comment]
> yea i did thinking it maybe was that .
> 
> but thx for the bug helping

that was never a Bug 🗡️
