### ISSUE TITLE
[Bug]: Discord/Bastion Not starting correctly

### ISSUE THREAD

**Issue by hoechstn** [parkervcp/eggs#1365]
### Panel Version

1.6.2

### Wings Version

1.5.1

### Service

Discord/Bastion

### Modified

No, I did not modify the egg

### Expected Behavior

No errors in console. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/11903937/137634094-2ee87615-d525-4109-a31d-c7cfc71da79e.png)
![image](https://user-images.githubusercontent.com/11903937/137634160-7befb902-a605-4e51-bbf0-82711c408cbd.png)
![image](https://user-images.githubusercontent.com/11903937/137634173-07cbdac2-3fcc-4d05-aeec-2ff7af1b9942.png)

not following variables set in Activity

### Steps To Reproduce

install on pterodactyl 

### Relevant log output

```shell
'[ERROR Sun Oct 17 2021 08:21:15 GMT-0700 (Pacific Daylight Time)]
MongooseError: Operation `configs.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Trace
    at Function.TesseractLogger.error (/home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3759)
    at TesseractClient.<anonymous> (/home/container/node_modules/@bastion/tesseract/dist/listeners/ListenerModuleManager.js:1:3972)
[ERROR]
[ERROR Sun Oct 17 2021 08:22:11 GMT-0700 (Pacific Daylight Time)]
TypeError: Cannot read property 'findById' of undefined
    at CommandManager.handle (/home/container/node_modules/@bastion/tesseract/dist/commands/CommandModuleManager.js:1:7449)
    at TesseractClient.<anonymous> (/home/container/node_modules/@bastion/tesseract/dist/commands/CommandModuleManager.js:1:4721)
    at TesseractClient.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/container/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/container/node_modules/ws/lib/receiver.js:78:10)
Trace
    at Function.TesseractLogger.error (/home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3759)
    at TesseractClient.<anonymous> (/home/container/node_modules/@bastion/tesseract/dist/commands/CommandModuleManager.js:1:4804)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR]
[ERROR Sun Oct 17 2021 08:22:12 GMT-0700 (Pacific Daylight Time)]
DiscordAPIError: Unknown Webhook
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async GuildCreateListener.<computed> (/home/container/listeners/guildCreate.js:1:2974)
    at async TesseractClient.<anonymous> (/home/container/node_modules/@bastion/tesseract/dist/listeners/ListenerModuleManager.js:1:3853) {
  method: 'get',
  path: '/webhooks/701415951563751434/picQLbDd6n_DfWzgaWVwVUQVsHfMpn0vD8vTe0WIALCUI5lFuYZ-81j9d1AoqJFAkMO2',
  code: 10015,
  httpStatus: 404
}
Trace
    at Function.TesseractLogger.error (/home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3759)
    at TesseractClient.<anonymous> (/home/container/node_modules/@bastion/tesseract/dist/listeners/ListenerModuleManager.js:1:3972)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR]
[ERROR Sun Oct 17 2021 08:22:21 GMT-0700 (Pacific Daylight Time)]
MongooseError: Operation `guilds.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Trace
    at TesseractLogger.error (/home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3759)
[ERROR]'
```

**Comment by 2zla** [comment]
Receiving this error upon install:

```
container@pterodactyl~ Starting installation process, this could take a few minutes...
fatal: destination path '.' already exists and is not an empty directory.
yarn install v1.22.18
info No lockfile found.
[1/4] Resolving packages...
warning @bastion/tesseract > cron@1.8.3: Breaking dependency change (moved from moment to luxon). Please move to 2.0.0.
warning @bastion/tesseract > discord.js > @discordjs/form-data@3.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @bastion/tesseract > discord.js > @discordjs/collection@0.1.6: no longer supported
warning gamedig > gbxremote > event-to-promise@0.7.0: Use promise-toolbox/fromEvent instead
warning youtube-dl > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning youtube-dl > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning youtube-dl > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning youtube-dl > request > har-validator@5.1.5: this library is no longer supported
warning @types/mathjs@9.4.2: This is a stub types definition. mathjs provides its own type definitions, so you do not need this installed.
[2/4] Fetching packages...
error yaml@2.1.3: The engine "node" is incompatible with this module. Expected version ">= 14". Got "12.22.12"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
mv: cannot stat 'settings/credentials.example.yaml': No such file or directory
mv: cannot stat 'settings/configurations.example.yaml': No such file or directory
mkdir: cannot create directory 'mongodb/': File exists

```

Looks like the cause is the egg is using node 12.22.12 when the installer is expecting node version >14

**Comment by parkervcp** [comment]
things may have changed on their end.
