### ISSUE TITLE
[Bug]: Error when starting Magma egg

### ISSUE THREAD

**Issue by iSoul-Es** [parkervcp/eggs#1480]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

Minecraft

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start, Play.

### Actual Behavior

An error appears and from what I understand it is because now the magma .jar opens a panel when opened and lets you select whether to install client or server.

### Steps To Reproduce

Step 1 : Create a server with pterodactyl
Step 2: Select Magma Egg and 1.16.5 settings 
Step 3: Start the server

### Relevant log output

```shell
Exeption in thread "main"
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requieres it
     at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
     at java.awt.Window.<init>(Window.java:536)
     at java.awt.Frame.<init>(Frame.java:420)
     at java.awt.Frame.<init>(Frame.java:385)
     at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763)
     at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838)
     at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
     at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
     at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
     at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
     at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
     at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)
```

**Comment by parkervcp** [comment]
This regularly happens because a client install was done and not a server.

**Comment by parkervcp** [comment]
This must be a recent change in their end because it worked before.

**Comment by iSoul-Es** [comment]
its only happens in magma 1.16.5 jar files

**Comment by iSoul-Es** [comment]
1.12.2 works fine

**Comment by Software-Noob** [comment]
1.16.5 contains an installer similar to Forge. We'd have to apply yet another logic to detect different versions
