### ISSUE TITLE
[Bug]: Project Zomboid server crashes on boot

### ISSUE THREAD

**Issue by zerfl** [parkervcp/eggs#1501]
### Panel Version

1.6.6

### Wings Version

1.5.3

### Service

project_zomboid

### Modified

No, I did not modify the egg

### Expected Behavior

Configure and install the server, the game daemon running and working.

I've also tried to change the docker image described in #1462 to ghcr.io/pterodactyl/games:source but it crashes just the same with the same log.

### Actual Behavior

It throws several File Not Found exceptions during boot and then crashes:

```
java.io.FileNotFoundException: /nonexistent/Zomboid/server-console.txt (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at zombie.network.GameServer.main(GameServer.java:295)
.
.
.
LOG  : General     , 1640588866246> 3,049,081,493> user database "/nonexistent/Zomboid/db/"MyServer".db"
ERROR: General     , 1640588866246> 3,049,081,493> java.io.IOException: No such file or directory
ERROR: General     , 1640588866246> 3,049,081,494>      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
ERROR: General     , 1640588866247> 3,049,081,494>      at java.base/java.io.File.createNewFile(Unknown Source)
ERROR: General     , 1640588866247> 3,049,081,494>      at zombie.network.ServerWorldDatabase.create(ServerWorldDatabase.java:310)
ERROR: General     , 1640588866247> 3,049,081,495>      at zombie.network.GameServer.main(GameServer.java:608)
LOG  : General     , 1640588866248> 3,049,081,495> failed to create user database, server shut down
```

### Steps To Reproduce

1) Download and install egg: https://github.com/parkervcp/eggs/blob/1005f7e95110b4297083c792852842a24e0db7d5/game_eggs/steamcmd_servers/project_zomboid/egg-project-zomboid.json
2) Create a new server, allocate proper ports and so on
3) Wait for server to crash after installation

### Relevant log output

```shell
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/games 
Digest: sha256:24b378b45bcab999eba5d7ed68a5f421c2b9294cd086f645de34e5c35ba85749 
Status: Image is up to date for ghcr.io/pterodactyl/games:source 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.

Using anonymous user.

No appid set. Starting Server
container@pterodactyl~ /home/container/start-server.sh -port 8766 -steamport1 8766 -servername "MyServer" -adminusername randomusername -adminpassword randompassword
64-bit java detected
ERROR: ld.so: object 'libjsig.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
pzexe: looking for PZXInitThreads.so
pzexe: libPZXInitThreads64.so was not found. This is ok for a server, but multi-core rendering won't work on a client without it.
pzexe: about to run java hack to locate libjvm.so...
pzexe: executing "java -classpath pzexe.jar -Djava.library.path=. zombie.pzexe"
ERROR: ld.so: object 'libjsig.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
pzexe.java: loading shared library "pzexe_jni64"
JVM=/home/container/jre64/lib/server/libjvm.so
pxexe: /proc/self/exe=/home/container/ProjectZomboid64
pzexe config file: /home/container/ProjectZomboid64.json
pzexe: mainClass: zombie/network/GameServer
pzexe: classpath: -Djava.class.path=java/.:java/istack-commons-runtime.jar:java/jassimp.jar:java/javacord-2.0.17-shaded.jar:java/javax.activation-api.jar:java/jaxb-api.jar:java/jaxb-runtime.jar:java/lwjgl.jar:java/lwjgl-natives-linux.jar:java/lwjgl-glfw.jar:java/lwjgl-glfw-natives-linux.jar:java/lwjgl-jemalloc.jar:java/lwjgl-jemalloc-natives-linux.jar:java/lwjgl-opengl.jar:java/lwjgl-opengl-natives-linux.jar:java/lwjgl_util.jar:java/sqlite-jdbc-3.27.2.1.jar:java/trove-3.0.3.jar:java/uncommons-maths-1.2.3.jar
pzexe: vmArg (json) 1: -Djava.awt.headless=true
pzexe: vmArg (json) 2: -Xmx8g
pzexe: vmArg (json) 3: -Dzomboid.steam=1
pzexe: vmArg (json) 4: -Dzomboid.znetlog=1
pzexe: vmArg (json) 5: -Djava.library.path=linux64/:natives/
pzexe: vmArg (json) 6: -Djava.security.egd=file:/dev/urandom
pzexe: vmArg (json) 7: -XX:+UseZGC
pzexe: vmArg (json) 8: -XX:-OmitStackTraceInFastThrow
pzexe: using jvm "/home/container/jre64/lib/server/libjvm.so"
pzexe: arg: -port
pzexe: arg: 8766
pzexe: arg: -steamport1
pzexe: arg: 8766
pzexe: arg: -servername
pzexe: arg: "MyServer"
pzexe: arg: -adminusername
pzexe: arg: randomusername
pzexe: arg: -adminpassword
pzexe: arg: randompassword
java.io.FileNotFoundException: /nonexistent/Zomboid/server-console.txt (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at zombie.network.GameServer.main(GameServer.java:295)
DEBUG: General     , 1640588865389> 3,049,080,643> LoggerManager.init                  > Initializing...
ERROR: General     , 1640588865415> 3,049,080,662> java.io.FileNotFoundException: /nonexistent/Zomboid/Logs/27-12-21_07-07-45_DebugLog-server.txt (No such file or directory)
ERROR: General     , 1640588865416> 3,049,080,663>      at java.base/java.io.FileOutputStream.open0(Native Method)
ERROR: General     , 1640588865416> 3,049,080,663>      at java.base/java.io.FileOutputStream.open(Unknown Source)
ERROR: General     , 1640588865416> 3,049,080,663>      at java.base/java.io.FileOutputStream.<init>(Unknown Source)
ERROR: General     , 1640588865416> 3,049,080,663>      at java.base/java.io.FileOutputStream.<init>(Unknown Source)
ERROR: General     , 1640588865416> 3,049,080,663>      at java.base/java.io.PrintStream.<init>(Unknown Source)
ERROR: General     , 1640588865416> 3,049,080,663>      at zombie.core.logger.ZLogger.<init>(ZLogger.java:32)
ERROR: General     , 1640588865416> 3,049,080,664>      at zombie.core.logger.LoggerManager.createLogger(LoggerManager.java:130)
ERROR: General     , 1640588865417> 3,049,080,664>      at zombie.core.logger.LoggerManager.getLogger(LoggerManager.java:20)
ERROR: General     , 1640588865417> 3,049,080,664>      at zombie.debug.DebugLog.init(DebugLog.java:376)
ERROR: General     , 1640588865417> 3,049,080,664>      at zombie.network.GameServer.main(GameServer.java:306)
LOG  : General     , 1640588865418> 3,049,080,666> cachedir set to "/nonexistent/Zomboid"
LOG  : General     , 1640588865476> 3,049,080,723> versionNumber=41.65 demo=false
LOG  : General     , 1640588865477> 3,049,080,724> svnRevision= date= time=
LOG  : General     , 1640588865478> 3,049,080,725> server name is ""MyServer""
LOG  : General     , 1640588865478> 3,049,080,725> map_t.bin does not exist, cannot determine the server's WorldVersion.  This is ok the first time a server is started.
LOG  : General     , 1640588865479> 3,049,080,726> Loading networking libraries...
LOG  : General     , 1640588865479> 3,049,080,727> Loading steam_api...
LOG  : General     , 1640588865480> 3,049,080,727> Loading RakNet64...
LOG  : General     , 1640588865480> 3,049,080,728> Loading ZNetJNI64...
LOG  : General     , 1640588865484> 3,049,080,731> 1640588865481 znet: ZNet loaded
LOG  : General     , 1640588865485> 3,049,080,732> 1640588865485 znet: Compiled with SERVER_STEAMAPI == 0
LOG  : General     , 1640588865485> 3,049,080,732> 1640588865485 znet: Starting with bServer == true
LOG  : General     , 1640588865485> 3,049,080,732> 1640588865485 znet: SteamAPI initialised successfully
LOG  : General     , 1640588865486> 3,049,080,733> SteamUtils initialised successfully
LOG  : General     , 1640588865495> 3,049,080,742> ERROR: Missing translation "UI_ServerOptionDesc_Help"
LOG  : General     , 1640588865495> 3,049,080,742> ERROR: Missing translation "UI_ServerOptionDesc_ChangePwd"
LOG  : General     , 1640588865495> 3,049,080,743> ERROR: Missing translation "UI_ServerOptionDesc_Roll"
LOG  : General     , 1640588865496> 3,049,080,743> ERROR: Missing translation "UI_ServerOptionDesc_Card"
LOG  : General     , 1640588865496> 3,049,080,743> ERROR: Missing translation "UI_ServerOptionDesc_SafeHouse"
LOG  : General     , 1640588865499> 3,049,080,746> creating server spawnregions file "/nonexistent/Zomboid/Server/"MyServer"_spawnregions.lua"
ERROR: General     , 1640588865500> 3,049,080,747> java.io.IOException: No such file or directory
ERROR: General     , 1640588865500> 3,049,080,747>      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
ERROR: General     , 1640588865500> 3,049,080,747>      at java.base/java.io.File.createNewFile(Unknown Source)
ERROR: General     , 1640588865500> 3,049,080,747>      at zombie.network.ServerOptions.initSpawnRegionsFile(ServerOptions.java:239)
ERROR: General     , 1640588865500> 3,049,080,747>      at zombie.network.ServerOptions.init(ServerOptions.java:222)
ERROR: General     , 1640588865500> 3,049,080,748>      at zombie.network.GameServer.main(GameServer.java:449)
LOG  : General     , 1640588865501> 3,049,080,748> writing /nonexistent/Zomboid/Server/"MyServer".ini
ERROR: General     , 1640588865501> 3,049,080,748> java.io.FileNotFoundException: /nonexistent/Zomboid/Server/"MyServer".ini (No such file or directory)
ERROR: General     , 1640588865502> 3,049,080,749>      at java.base/java.io.FileOutputStream.open0(Native Method)
ERROR: General     , 1640588865502> 3,049,080,749>      at java.base/java.io.FileOutputStream.open(Unknown Source)
ERROR: General     , 1640588865502> 3,049,080,749>      at java.base/java.io.FileOutputStream.<init>(Unknown Source)
ERROR: General     , 1640588865502> 3,049,080,749>      at java.base/java.io.FileWriter.<init>(Unknown Source)
ERROR: General     , 1640588865502> 3,049,080,749>      at zombie.config.ConfigFile.write(ConfigFile.java:86)
ERROR: General     , 1640588865503> 3,049,080,750>      at zombie.network.ServerOptions.saveServerTextFile(ServerOptions.java:569)
ERROR: General     , 1640588865503> 3,049,080,750>      at zombie.network.ServerOptions.init(ServerOptions.java:223)
ERROR: General     , 1640588865503> 3,049,080,750>      at zombie.network.GameServer.main(GameServer.java:449)
LOG  : General     , 1640588865504> 3,049,080,751> 1640588865504 znet: Java_zombie_core_znet_SteamGameServer_Init
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
Setting breakpad minidump AppID = 108600
LOG  : General     , 1640588865535> 3,049,080,782> 1640588865535 znet: SteamGameServer seems to be initialized
LOG  : General     , 1640588865535> 3,049,080,782> 1640588865535 znet: Java_zombie_core_znet_SteamGameServer_SetProduct
LOG  : General     , 1640588865535> 3,049,080,783> 1640588865535 znet: Java_zombie_core_znet_SteamGameServer_SetGameDescription
LOG  : General     , 1640588865536> 3,049,080,783> 1640588865536 znet: Java_zombie_core_znet_SteamGameServer_SetModDir
LOG  : General     , 1640588865536> 3,049,080,783> 1640588865536 znet: Java_zombie_core_znet_SteamGameServer_SetDedicatedServer
LOG  : General     , 1640588865536> 3,049,080,783> 1640588865536 znet: Java_zombie_core_znet_SteamGameServer_SetMaxPlayerCount
LOG  : General     , 1640588865537> 3,049,080,784> 1640588865537 znet: Java_zombie_core_znet_SteamGameServer_SetServerName 'My PZ Server'
LOG  : General     , 1640588865537> 3,049,080,784> 1640588865537 znet: Java_zombie_core_znet_SteamGameServer_SetMapName 'Muldraugh, KY'
LOG  : General     , 1640588865537> 3,049,080,785> 1640588865537 znet: Java_zombie_core_znet_SteamGameServer_SetGameTags 'hidden'
LOG  : General     , 1640588865538> 3,049,080,785> 1640588865538 znet: Java_zombie_core_znet_SteamGameServer_SetKeyValue key='description' value=''
LOG  : General     , 1640588865538> 3,049,080,785> 1640588865538 znet: Java_zombie_core_znet_SteamGameServer_SetKeyValue key='version' value='41.65'
LOG  : General     , 1640588865539> 3,049,080,786> 1640588865539 znet: Java_zombie_core_znet_SteamGameServer_SetKeyValue key='open' value='1'
LOG  : General     , 1640588865539> 3,049,080,786> 1640588865539 znet: Java_zombie_core_znet_SteamGameServer_SetKeyValue key='public' value='0'
LOG  : General     , 1640588865539> 3,049,080,786> 1640588865539 znet: Java_zombie_core_znet_SteamGameServer_SetKeyValue key='mods' value=''
LOG  : General     , 1640588865540> 3,049,080,787> 1640588865540 znet: Java_zombie_core_znet_SteamWorkshop_n_1Init
LOG  : General     , 1640588865541> 3,049,080,788> 1640588865541 znet: Java_zombie_core_znet_SteamGameServer_LogOnAnonymous
LOG  : General     , 1640588865541> 3,049,080,788> 1640588865541 znet: Java_zombie_core_znet_SteamGameServer_EnableHeartBeats
LOG  : General     , 1640588865541> 3,049,080,788> Waiting for response from Steam servers
LOG  : General     , 1640588866243> 3,049,081,490> 1640588866243 znet: OnSteamServersConnected
LOG  : General     , 1640588866244> 3,049,081,491> 1640588866244 znet: Public IP: xxx.xxx.xxx.xxx
LOG  : General     , 1640588866246> 3,049,081,493> user database "/nonexistent/Zomboid/db/"MyServer".db"
ERROR: General     , 1640588866246> 3,049,081,493> java.io.IOException: No such file or directory
ERROR: General     , 1640588866246> 3,049,081,494>      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
ERROR: General     , 1640588866247> 3,049,081,494>      at java.base/java.io.File.createNewFile(Unknown Source)
ERROR: General     , 1640588866247> 3,049,081,494>      at zombie.network.ServerWorldDatabase.create(ServerWorldDatabase.java:310)
ERROR: General     , 1640588866247> 3,049,081,495>      at zombie.network.GameServer.main(GameServer.java:608)
LOG  : General     , 1640588866248> 3,049,081,495> failed to create user database, server shut down
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5086) : m_vecRegisteredWriters.Count() == 0
container@pterodactyl~ Server marked as offline...
```

**Comment by gOOvER** [comment]
there is a PR. you can test this:

https://github.com/parkervcp/eggs/pull/1475

**Comment by zerfl** [comment]
Thanks for linking the PR.

While the script allows for more variables to be set, it still crashes with the same logs after installation.
I am trying to debug this myself but I just can't find out why the game would be looking for the files in `/nonexistent/Zomboid/` (as that seems relevant to me in the logs).

**Comment by zerfl** [comment]
I fixed it by extending the startup command:
`-cachedir=/home/container/.cache` 

Any location inside /home/container should work, but I wanted to make sure it's in a separate directory. After the first boot all files will be properly created and the server runs just fine:
![image](https://user-images.githubusercontent.com/219458/147521501-2574a890-1008-49c1-a9a0-af84b4455c65.png)

Furthermore, I checked how the game server determines its configuration folders:
```java
    public String getCacheDir() {
        if (this.cacheDir == null) {
            String s = System.getProperty("deployment.user.cachedir");
            if (s == null || System.getProperty("os.name").startsWith("Win")) {
                s = System.getProperty("user.home");
            }
            this.setCacheDir(s + File.separator + "Zomboid");
        }
        return this.cacheDir.getPath();
    }
```

For whatever reason it returns `/nonexistent/Zomboid` in my container. Given this code I am not sure how other people were successfully able to run the linked PR or the original egg.

**Comment by Software-Noob** [comment]
I can't replicate this myself. The egg linked in the PR works fine. Based on the code it should set the cache dir itself unless overwritten otherwise.
![image](https://user-images.githubusercontent.com/10975908/147670561-3540845f-9cb1-4373-9f19-4e6bcfc0ba29.png)
