### ISSUE TITLE
[Bug]: magma No X11 DISPLAY variable was set,

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1516]
### Panel Version

latest

### Wings Version

latest

### Service

minecraft/magma

### Modified

No, I did not modify the egg

### Expected Behavior

No error. Server starts

### Actual Behavior

container@pterodactyl~ java -Xms128M -Xmx1024M -jar server.jar
JVM info: Oracle Corporation - 17.0.1 - 17.0.1+12-39
java.net.preferIPv4Stack=true
Found java version 17.0.1
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:676)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:647)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)

### Steps To Reproduce

Install magma egg

### Install logs

above

**Comment by Software-Noob** [comment]
Latest is not a version. Please fill the template correctly and provide the install logs, because you are trying to run the installer right now.

**Comment by parkervcp** [comment]
So far as I can tell. I just updated my egg and ran an install and it is working. No complaints so far. MC 1.12.2 with java 8.

**Comment by LeD0c4** [comment]
i've the same problem with 1.6.6 panel and the latest mohist egg

**Comment by Software-Noob** [comment]
> i've the same problem with 1.6.6 panel and the latest mohist egg

You have to provide the install logs for us to see what is going on

**Comment by LeD0c4** [comment]
now i don't no why i've an error at the end of the install
https://pastebin.com/AF4kLy1s

**Comment by Software-Noob** [comment]
> now i don't no why i've an error at the end of the install but i can't locate /mnt/install/install.sh
> https://pastebin.com/AF4kLy1s

I will take a look later today

**Comment by LeD0c4** [comment]
no problem thanks you

**Comment by LeD0c4** [comment]
the solution (for me) it's to write --installServer on the installation script after java arg

**Comment by Software-Noob** [comment]
> the solution (for me) it's to write --installServer on the installation script after java arg

The latest egg already does that. You're not using it if you are missing it from the install script.

`java -jar installer.jar --installServer || { echo -e "install failed" exit 4; }`

The issue is with me forgetting to leave a check for `latest` and instead only checking for exact versions or empty.
