### ISSUE TITLE
[Bug]: Space engineers remote API Unable to start

### ISSUE THREAD

**Issue by LetterN** [parkervcp/eggs#1602]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

Space engineers

### Modified

No, I did not modify the egg

### Expected Behavior

Server to start properly

### Actual Behavior

Server crashed with error in log, exiting.

```
2022-04-04 02:28:51.399 - Thread:  17 ->  Exception occurred: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.HttpListener..ctor()
   at VRage.Dedicated.RemoteAPI.MyRemoteServer.Listen()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   ```

### Steps To Reproduce

1. Start an SE server with the `ENABLE REMOTE API` set to `true`
2. Error happens

### Install logs

https://gist.github.com/LetterN/b1716e7208d8b17155280e9c37fc3a20

**Comment by LetterN** [comment]
might be related to https://github.com/parkervcp/eggs/issues/1400 as it "crashes" (exits) without errors (but the log will have it)

**Comment by Cyanoure** [comment]
I have the same problem. I enabled the remote api and it just exits without errors.
Without the remote api enabled, it starts with no problem.

**Comment by Cyanoure** [comment]
> I have the same problem. I enabled the remote api and it just exits without errors. Without the remote api enabled, it starts with no problem.

Ok, I found the same error message in the log file.

**Comment by gOOvER** [comment]
Please test this egg. I rewrote the egg, because the complete Installscript was wrong

https://github.com/gOOvER/parkervcp-eggs/tree/serewrite/game_eggs/steamcmd_servers/space_engineers

**Comment by LetterN** [comment]
Tested the egg, server starts with remote api however it keeps dropping the connection (connection refused)  might be a local issue, testing it.

**Comment by gOOvER** [comment]
possible, that eine dont Support remote API, because of Missing Support
