### ISSUE TITLE
[Bug]: BastionBot - Illegal instruction

### ISSUE THREAD

**Issue by gOOvER** [parkervcp/eggs#2009]
### Panel Version

1.11.2

### Wings Version

1.11.0

### Service

BastionBot

### Modified

No, I did not modify the egg

### Expected Behavior

Server should start

### Actual Behavior

There is an Error on Start

```
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ${STARTUP_CMD}
/entrypoint.sh: line 13:    15 Illegal instruction     (core dumped) mongod --fork --dbpath /home/container/mongodb/ --port 27017 --logpath /home/container/mongod.log
> bastion@10.4.0 start
> node .
```

Mongo dont start;

```
[ERROR]
/home/container/node_modules/mongoose/lib/connection.js:825
  const serverSelectionError = new ServerSelectionError();
                               ^
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Connection.openUri (/home/container/node_modules/mongoose/lib/connection.js:825:32)
    at /home/container/node_modules/mongoose/lib/index.js:417:10
    at /home/container/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/container/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/home/container/node_modules/mongoose/lib/index.js:1270:10)
    at Mongoose.connect (/home/container/node_modules/mongoose/lib/index.js:416:20)
    at TesseractClient.connectMongo (/home/container/node_modules/@bastion/tesseract/dist/TesseractClient.js:1:14373)
    at TesseractClient.init (/home/container/node_modules/@bastion/tesseract/dist/TesseractClient.js:1:14611)
    at Object.<anonymous> (/home/container/dist/bastion.js:61:9) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      '127.0.0.1:27017' => ServerDescription {
        address: '127.0.0.1:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 653475121,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
            at connectionFailureError (/home/container/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/home/container/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ECONNREFUSED 127.0.0.1:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
            errno: -111,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '127.0.0.1',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
```

### Steps To Reproduce

install latest Version of the BastionBot egg

### Install logs

https://pteropaste.com/uo5zgg/

**Comment by QuintenQVD0** [comment]
something is likly wrong on your end:
![afbeelding](https://user-images.githubusercontent.com/67589015/208097645-54f43c31-a455-47d4-8d5b-b3503471c79f.png)

**Comment by QuintenQVD0** [comment]
Even made a 2nd server no issue, Host OS Debian 11.5 kernel 5.10.0-19-amd64

**Comment by gOOvER** [comment]
ok, problem with MongoDB and Proxmox is, that MongoDB5 need a newer CPU and when the Server runs with KVM64, mongoDB5 dont start. As solution; in Proxmox VM the CPU must be changed to HOST
