### ISSUE TITLE
[Bug]: Discord Tickets crashing

### ISSUE THREAD

**Issue by slimshizn** [parkervcp/eggs#2209]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

Discord Tickets

### Modified

No, I did not modify the egg

### Expected Behavior

Server start, stay on unless stopped.

### Actual Behavior

Server crashes after opening a ticket.

### Steps To Reproduce

Install
Setup bot via instructions
Start bot
(ticket button created prior to update) Click the option under the bot in discord to open a ticket.
Bot crashes
Install log is not available. The bot was created and working for roughly a month.

To note: this was with the latest pull. Prior this problem didn't exist and the bot worked.

```
2023-03-30 09:46:32 [ERROR] DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ApplicationCommandPermissionsManager.set (/home/container/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:186:18)
    at async /home/container/src/modules/commands/manager.js:137:5
/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^
TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:528:14)
    ```

### Install logs

ls: /var/log/pterodactyl/install/*.log: No such file or directory

**Comment by QuintenQVD0** [comment]
1. This is not an offical egg
2. This is a coding issue
3. Contact the author of the egg
