### ISSUE TITLE
FiveM egg not handling restarts properly

### ISSUE THREAD

**Issue by SubtypeZero** [parkervcp/eggs#24]
I recently put up a FiveM server to play around with and created a schedule for automatic restarts since the server needs to be refreshed every so often (otherwise destroyed cars will pile up and make a huge mess). The server starts, restarts, and stops just fine when I manually click the appropriate buttons, but for some reason the schedule doesn't seem to handle this properly. I haven't watched it try to do a restart (I'll try to remember for next time), but when I check on it every couple days or so it always appears to be stuck on "Stopping" and I have to kill it several times to get rid of the queued up restarts before starting it back up again.

**Comment by parkervcp** [comment]
I have a server running daily restarts currently and see no issues with it. Can you get logs for it?

**Comment by SubtypeZero** [comment]
Sorry if this seems like it should be obvious, but which logs do you want me to submit? Either a file path or list of commands would help.

**Comment by parkervcp** [comment]
panel logs and server logs if possible

**Comment by SubtypeZero** [comment]
```
04:00:14.630Z  INFO wings: Server status has been changed to STOPPING (server=0dd15f40-5128-4c5b-9c18-bbb6bd7ece92)
04:00:15.602Z FATAL wings: (path=/v1/server/power, method=PUT)
    Error: Can't remove headers after they are sent
        at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:391:11)
        at ServerResponse.restifyWriteHead [as writeHead] (/srv/daemon/node_modules/restify/lib/response.js:426:14)
        at _cb (/srv/daemon/node_modules/restify/lib/response.js:326:14)
        at ServerResponse.send (/srv/daemon/node_modules/restify/lib/response.js:342:9)
        at Responses.generic204 (/srv/daemon/src/helpers/responses.js:35:25)
        at Object.Auth.server.restart.err [as callback] (/srv/daemon/src/controllers/routes.js:242:31)
        at /srv/daemon/node_modules/dockerode/lib/container.js:597:12
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
04:00:15.604Z FATAL wings: (path=/v1/server/power, method=PUT)
    Error: Can't remove headers after they are sent
        at ServerResponse.OutgoingMessage.removeHeader (_http_outgoing.js:391:11)
        at ServerResponse.restifyWriteHead [as writeHead] (/srv/daemon/node_modules/restify/lib/response.js:426:14)
        at _cb (/srv/daemon/node_modules/restify/lib/response.js:326:14)
        at ServerResponse.send (/srv/daemon/node_modules/restify/lib/response.js:342:9)
        at Responses.generic204 (/srv/daemon/src/helpers/responses.js:35:25)
        at Object.Auth.server.restart.err [as callback] (/srv/daemon/src/controllers/routes.js:242:31)
        at /srv/daemon/node_modules/dockerode/lib/container.js:597:12
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:91:20)
```

**Comment by parkervcp** [comment]
That looks like a panel/daemon issue not fivem related

**Comment by SubtypeZero** [comment]
Yeah, something isn't quite right with that server. Maybe I need to rebuild the container or something.

**Comment by parkervcp** [comment]
So as this looks like a panel related issue I am going to close this.
