### ISSUE TITLE
[Server crashing after install]: <RageCoop>

### ISSUE THREAD

**Issue by tommylee464** [parkervcp/eggs#2443]
### Panel Version

latest

### Wings Version

latest

### Service

GTA V

### Modified

No, I did not modify the egg

### Expected Behavior

Work

### Actual Behavior

container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:4f42b54a8fdba5e5d77be7003b4dbcc442b274eeb3ed4618c4ba939c8e232f92 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./RageCoop.Server
[08/27/2023 07:27:46][Server] [INF] ================
[08/27/2023 07:27:46][Server] [INF] Listening port: 2205
[08/27/2023 07:27:46][Server] [INF] Server version: 1.5.4.3
[08/27/2023 07:27:46][Server] [INF] Compatible client version: 1.5.4
[08/27/2023 07:27:46][Server] [INF] Runtime: linux-x64 => debian.11-x64
[08/27/2023 07:27:46][Server] [INF] ================
[08/27/2023 07:27:46][Server] [INF] Listening addresses:
[08/27/2023 07:27:46][Server] [INF] [lo]:
[08/27/2023 07:27:46][Server] [INF] 127.0.0.1
[08/27/2023 07:27:46][Server] [INF] ::1
[08/27/2023 07:27:46][Server] [INF]
[08/27/2023 07:27:46][Server] [INF] [eth0]:
container@pterodactyl~ Server marked as running...
[08/27/2023 07:27:46][Server] [INF] 172.18.0.4
[08/27/2023 07:27:46][Server] [INF] fdba:17c8:6c94::3
[08/27/2023 07:27:46][Server] [INF] fe80::42:acff:fe12:4%117
[08/27/2023 07:27:46][Server] [INF]
[08/27/2023 07:27:46][Server] [INF] Listening for clients
[08/27/2023 07:27:46][Server] [INF] Please use CTRL + C if you want to stop the server!
[08/27/2023 07:27:46][Server] [INF] Type here to send chat messages or execute commands
[08/27/2023 07:27:49][Server] [ERR] Error processing message
[08/27/2023 07:27:49][Server] [ERR]
Index was outside the bounds of the array.
[08/27/2023 07:27:49][Server] [TRC] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset)
   at Lidgren.Network.NetBuffer.ReadByte()
   at RageCoop.Server.Server.ProcessMessage(NetIncomingMessage message) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 171
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 18
[08/27/2023 07:27:49][Server] [ERR] Error receiving a packet of type Unknown
[08/27/2023 07:27:49][Server] [ERR] Index was outside the bounds of the array.
[08/27/2023 07:27:49][Server] [ERR]    at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset)
   at Lidgren.Network.NetBuffer.ReadByte()
   at RageCoop.Server.Server.ProcessMessage(NetIncomingMessage message) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 171
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 18
[08/27/2023 07:27:49][Server] [ERR] Unhandled exception thrown from user thread:Object reference not set to an instance of an object.
[08/27/2023 07:27:49][Server] [TRC] System.NullReferenceException: Object reference not set to an instance of an object.
   at RageCoop.Server.Server.DisconnectAndLog(NetConnection senderConnection, PacketType type, Exception e) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Connections.cs:line 18
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 26
   at RageCoop.Server.Server.<.ctor>b__39_0() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.cs:line 78
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RageCoop.Server.Server.DisconnectAndLog(NetConnection senderConnection, PacketType type, Exception e) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Connections.cs:line 18
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 26
   at RageCoop.Server.Server.<.ctor>b__39_0() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.cs:line 78
   at System.Threading.Thread.StartCallback()
/entrypoint.sh: line 13:    13 Aborted                 (core dumped) ./RageCoop.Server
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:4f42b54a8fdba5e5d77be7003b4dbcc442b274eeb3ed4618c4ba939c8e232f92 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./RageCoop.Server
[08/27/2023 07:27:52][Server] [INF] ================
[08/27/2023 07:27:52][Server] [INF] Listening port: 2205
[08/27/2023 07:27:52][Server] [INF] Server version: 1.5.4.3
[08/27/2023 07:27:52][Server] [INF] Compatible client version: 1.5.4
[08/27/2023 07:27:52][Server] [INF] Runtime: linux-x64 => debian.11-x64
[08/27/2023 07:27:52][Server] [INF] ================
[08/27/2023 07:27:52][Server] [INF] Listening addresses:
[08/27/2023 07:27:52][Server] [INF] [lo]:
[08/27/2023 07:27:52][Server] [INF] 127.0.0.1
[08/27/2023 07:27:52][Server] [INF] ::1
[08/27/2023 07:27:52][Server] [INF]
[08/27/2023 07:27:52][Server] [INF] [eth0]:
[08/27/2023 07:27:52][Server] [INF] 172.18.0.4
[08/27/2023 07:27:52][Server] [INF] fdba:17c8:6c94::3
[08/27/2023 07:27:52][Server] [INF] fe80::42:acff:fe12:4%119
[08/27/2023 07:27:52][Server] [INF]
[08/27/2023 07:27:52][Server] [INF] Listening for clients
container@pterodactyl~ Server marked as running...
[08/27/2023 07:27:52][Server] [INF] Please use CTRL + C if you want to stop the server!
[08/27/2023 07:27:52][Server] [INF] Type here to send chat messages or execute commands
[08/27/2023 07:27:54][Server] [ERR] Error processing message
[08/27/2023 07:27:54][Server] [ERR]
Index was outside the bounds of the array.
[08/27/2023 07:27:54][Server] [TRC] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset)
   at Lidgren.Network.NetBuffer.ReadByte()
   at RageCoop.Server.Server.ProcessMessage(NetIncomingMessage message) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 171
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 18
[08/27/2023 07:27:54][Server] [ERR] Error receiving a packet of type Unknown
[08/27/2023 07:27:54][Server] [ERR] Index was outside the bounds of the array.
[08/27/2023 07:27:54][Server] [ERR]    at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset)
   at Lidgren.Network.NetBuffer.ReadByte()
   at RageCoop.Server.Server.ProcessMessage(NetIncomingMessage message) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 171
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 18
[08/27/2023 07:27:54][Server] [ERR] Unhandled exception thrown from user thread:Object reference not set to an instance of an object.
[08/27/2023 07:27:54][Server] [TRC] System.NullReferenceException: Object reference not set to an instance of an object.
   at RageCoop.Server.Server.DisconnectAndLog(NetConnection senderConnection, PacketType type, Exception e) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Connections.cs:line 18
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 26
   at RageCoop.Server.Server.<.ctor>b__39_0() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.cs:line 78
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RageCoop.Server.Server.DisconnectAndLog(NetConnection senderConnection, PacketType type, Exception e) in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Connections.cs:line 18
   at RageCoop.Server.Server.Listen() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.Listener.cs:line 26
   at RageCoop.Server.Server.<.ctor>b__39_0() in D:\a\RAGECOOP-V\RAGECOOP-V\RageCoop.Server\Networking\Server.cs:line 78
   at System.Threading.Thread.StartCallback()
/entrypoint.sh: line 13:    13 Aborted                 (core dumped) ./RageCoop.Server
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

1. import the latest ragecoop eggs from git.
2. create a new rage coop server.
3. go in console.
and you see the message in actual behavior :D.

### Install logs

https://pteropaste.com/0hf9vj0ghs0s

**Comment by tommylee464** [comment]
I finally found the problem it was the memory allocation for the server was too high! :D
