### ISSUE TITLE
[Bug]: V-Rising BepinEx

### ISSUE THREAD

**Issue by asthomas** [parkervcp/eggs#2456]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

V-Rising BepinEx

### Modified

No, I did not modify the egg

### Expected Behavior

Starting the server should work.

### Actual Behavior

Server continually tries to start, encounters an error setting up Wine, then starts from the beginning again.

The below sequence repeats forever.  The failure is during installation of dotnet-runtime-6.0.19-win-x86.exe. 

```
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:51c8bc540cc23b9fc915c8f75893fbd625349a09fcb692a5442ed256d6f50fd7 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_staging 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.7
Current timezone: Etc/UTC
wine-8.14 (Staging)
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1691628584
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '1829350' already up to date.
First launch will throw some errors. Ignore them
Installing vcrun2019
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 with wine-8.14 (Staging) and WINEARCH=win64
Executing w_do_call vcrun2019
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2019 
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcp140_atomic_wait msvcp140_codecvt_ids vcamp140 vccorlib140 vcomp140 vcruntime140
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
------------------------------------------------------
warning: Working around wine bug 50894 -- Working around failing wusa.exe lookup via C:\windows\SysNative
------------------------------------------------------
Executing wine winecfg -v winxp64
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/container/.wine terminate
------------------------------------------------------
Executing cd /home/container/.cache/winetricks/vcrun2019
Executing wine vc_redist.x86.exe /q
Using native,builtin override for following DLLs: vcruntime140_1
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing wine vc_redist.x64.exe /q
Executing w_do_call ucrtbase2019
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
ucrtbase2019 already installed, skipping
------------------------------------------------------
warning: Unsupported Windows version winxp64
------------------------------------------------------
Installing dotnet48
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 with wine-8.14 (Staging) and WINEARCH=win64
Executing w_do_call dotnet48
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet48 
------------------------------------------------------
warning: This package (dotnet48) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono internal
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono internal
reg: Unable to find the specified registry key
reg: The operation completed successfully
Executing rm -f /home/container/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing rm -f /home/container/.wine/dosdevices/c:/windows/syswow64/mscoree.dll
Executing w_do_call dotnet40
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet40 
------------------------------------------------------
warning: This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
------------------------------------------------------
warning: dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing w_do_call remove_mono internal
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono internal
reg: Unable to find the specified registry key
reg: Unable to find the specified registry key
Executing rm -f /home/container/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing rm -f /home/container/.wine/dosdevices/c:/windows/syswow64/mscoree.dll
Executing w_do_call winxp
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_winxp 
Executing wine winecfg -v winxp64
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/container/.wine terminate
------------------------------------------------------
Executing cd /home/container/.cache/winetricks/dotnet40
Executing wine dotNetFx40_Full_x86_x64.exe /q /c:install.exe /q
Using native override for following DLLs: mscoree
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
Executing wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
reg: The operation completed successfully
reg: The operation completed successfully
reg: The operation completed successfully
------------------------------------------------------
warning: Unsupported Windows version winxp64
------------------------------------------------------
Installing dotnet6
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: be4196ba3358be7c68cb58e7a7cbe9b37418e12e92beb88876e119998f438532 with wine-8.14 (Staging) and WINEARCH=win64
Executing w_do_call dotnet6
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet6 
Executing cd /home/container/.cache/winetricks/dotnet6
Executing wine dotnet-runtime-6.0.19-win-x86.exe /quiet
------------------------------------------------------
warning: Note: command wine dotnet-runtime-6.0.19-win-x86.exe /quiet returned status 1. Aborting.
------------------------------------------------------
:/home/container$ WINEDLLOVERRIDES="winhttp=n,b"; xvfb-run wine ./VRisingServer.exe -persistentDataPath save-data -address 0.0.0.0
container@pterodactyl~ Server marked as offline...
```

### Steps To Reproduce

Attempt to run V-Rising BepinEx egg on Ubuntu 22.04 LTS.

### Install logs

https://pteropaste.com/xec9yrpcjpxs

**Comment by QuintenQVD0** [comment]
Try removing the .wine and .cache. then hit start again. And be certain you still have disk space.

**Comment by asthomas** [comment]
Thanks for responding.  I removed both of those folders, and the startup definitely improved.  All the Windows packages installed correctly, and so apparently did the V-Rising server.  Now I get a runtime error in BepinEx:
```
[Message: Preloader] BepInEx 6.0.0-be.668 - VRisingServer
[Message: Preloader] Built from commit 46e297f210c27e9b4d26e7cd326625b53c83faa0
[Info   :   BepInEx] System platform: Windows 7 (Wine 8.15) 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2020.3.46f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.File.ReadAllBytes(String path)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 203
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 61
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 67
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.RunCpp2Il() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 278
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssemblies() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 213
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
Initialize engine version: 2020.3.46f1 (18bc01a066b4)
[Subsystems] Discovering subsystems at path Z:/home/container/VRisingServer_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5233:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM default
FMOD initialized on nosound output
wine: Unhandled exception 0xe0434352 in thread 478 at address 0000000174013A77 (thread 0478), starting debugger...
```
I'm guessing that the ALSA errors are irrelevant here.

The apparent problem is with this: Failed to generate Il2Cpp interop assemblies: System.OutOfMemoryException at System.IO.File.ReadAllBytes(String path).
I have provided 10 GB of memory for the server, of which it is using 2 GB.
I have provided 100 GB of disk space, of which it is using 5 GB.  According to 'df', there is 200 GB of disk available on the volume.

Is this a problem with Wine, with BepinEx, or with my configuration?

**Comment by asthomas** [comment]
FWIW, the non-BepinEx egg runs fine.

So, I copied the non-BepinEx egg and modified it to add the BepinEx download code from the VRising BepinEx egg, modified the installation to grab the extra utilities and modified the startup command to add the WINEDLLOVERRIDES envar.  Starting with or without xvfb-run produces the same out-of-memory error as above when loading BepinEx.

What else can I try?

**Comment by gOOvER** [comment]
try wine stable as image

**Comment by asthomas** [comment]
I tried both wine_devel and wine_latest with and without my egg hacks.  

With my egg hacks, wine_latest generates: wine: could not load kernel32.dll, status c0000135
Without my hacks, wine_latest: VRisingServer.exe crashes silently at startup

wine_devel behaves the same as wine_latest.

**Comment by QuintenQVD0** [comment]
> I tried both wine_devel and wine_latest with and without my egg hacks.
> 
> With my egg hacks, wine_latest generates: wine: could not load kernel32.dll, status c0000135 Without my hacks, wine_latest: VRisingServer.exe crashes silently at startup
> 
> wine_devel behaves the same as wine_latest.

If you switch wine version you need to remove the .wine and .cache folder

**Comment by asthomas** [comment]
On each experiment I have completely deleted the server and started from scratch each time.  After the first run, which always failed, I deleted the .wine and .cache folders and ran it again.  I believe that makes a clean test each time.

**Comment by gOOvER** [comment]
then ist could be a problem with bepinex

**Comment by MaXx-62** [comment]
> then ist could be a problem with bepinex

I have a question nothing to do with the problem, I saw that the eggs bepinex in the startup command there is this **-address 0.0.0.0**

I have an anti-ddos, and when I put the ip of the anti-ddos, the server starts well, but impossible to connect, is it mandatory 0.0.0.0 ?

**Comment by gOOvER** [comment]
> > then ist could be a problem with bepinex
> 
> I have a question nothing to do with the problem, I saw that the eggs bepinex in the startup command there is this **-address 0.0.0.0**
> 
> I have an anti-ddos, and when I put the ip of the anti-ddos, the server starts well, but impossible to connect, is it mandatory 0.0.0.0 ?

0.0.0.0 bian all aviable ips. you can change it to everything you want

**Comment by MaXx-62** [comment]
> 0.0.0.0 bind all aviable ips. you can change it to everything you want. I cant remember, if this is needed.

Right, because when I change with the ip of my anti-ddos that uses a gre tunnel, it doesn't work :(

only 0.0.0.0 work

**Comment by gOOvER** [comment]
> > 0.0.0.0 bind all aviable ips. you can change it to everything you want. I cant remember, if this is needed.
> 
> Right, because when I change with the ip of my anti-ddos that uses a gre tunnel, it doesn't work :(
> 
> only 0.0.0.0 work

then stay on 0.0.0.0. i dont see any problem here

**Comment by gOOvER** [comment]
For all other @MaXx-62 use discord and stop highjacking a ticket

**Comment by MaXx-62** [comment]
> For all other @MaXx-62 use discord and stop highjacking a ticket

Which discord? and I managed to use anti-ddos but when I want to turn on a 2nd server I get an xvfb error

![image](https://github.com/parkervcp/eggs/assets/4140252/ae66f530-212b-433a-b129-489002d7e6f3)

**Comment by MaXx-62** [comment]
> For all other @MaXx-62 use discord and stop highjacking a ticket

ok thx, discord pterodactyl or another ?

**Comment by QuintenQVD0** [comment]
> > For all other @MaXx-62 use discord and stop highjacking a ticket
> 
> ok thx, discord pterodactyl or another ?

ofc offical pterodactyl discord

**Comment by QuintenQVD0** [comment]
This should have been fixt with #2550
