### ISSUE TITLE
[Bug]: <Egg Name>

### ISSUE THREAD

**Issue by cc3768** [parkervcp/eggs#2502]
### Panel Version

1.11.4

### Wings Version

1.11.8

### Service

minecraft/java/ftb/egg-ftb-modpacksch-server.json

### Modified

No, I did not modify the egg

### Expected Behavior

The server to start and run correctly.

### Actual Behavior

container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:0d342f7f0b77fb72d174f15c6f9e61ec12c3fab990d2330d1354863e364c7b5a 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)
container@pterodactyl~ java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar start-server.jar
JVM info: Eclipse Adoptium - 17.0.8.1 - 17.0.8.1+1
java.net.preferIPv4Stack=true
Current Time: 11/10/2023 07:15:11
Host: files.minecraftforge.net [51.79.83.165]
Host: maven.minecraftforge.net [51.79.83.165]
Host: libraries.minecraft.net [13.107.246.36, 13.107.213.36]
Host: launchermeta.mojang.com [13.107.246.36, 13.107.213.36]
Host: piston-meta.mojang.com [13.107.213.36, 13.107.246.36]
Host: authserver.mojang.com [3.162.3.92, 3.162.3.54, 3.162.3.13, 3.162.3.93]
Found java version 17.0.8.1
Following redirect: https://neoforged.net/mirrorlist.json
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:676)
        at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:647)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:191)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:161)

### Steps To Reproduce

1: Install Egg
2: setup Egg
3: Create a Server
4: Setup the Server
5: (It will never launch but will install correctly)

### Install logs

https://pteropaste.com/m8saxd3f0xjd/

**Comment by F9Alejandro** [comment]
Issue solved need to use --installserver as part of the starting args.
See https://github.com/MinecraftForge/Installer/blob/master/src/main/java/net/minecraftforge/installer/SimpleInstaller.java under OptionSpecBuilder, nogui is not an option and no option used will cause it to try and load a gui on a headless (no display/monitor) device/server.

```java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true $( [[  ! -f unix_args.txt ]] && printf %s "-jar start-server.jar --installserver" || printf %s "@unix_args.txt" )```
