### ISSUE TITLE
[Install Bug]: curseforge

### ISSUE THREAD

**Issue by Serph91P** [parkervcp/eggs#2599]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Minecraft/Forge

### Modified

No, I did not modify the egg

### Expected Behavior

The Modpack to install and run the server.

### Actual Behavior

Install hangs at:

```
Starting installation process, this could take a few minutes...
Installing required packages...
        Running apt update
        Running apt install
Retrieving CurseForge project information...
        Checking if provided file id '4787500' exists
        Retrieving version information for '4787500'
        Parsing CurseForge pack download url
        Downloading https://edge.forgecdn.net/files/4787/500/Server-Files-1.0.28.zip
Retrieving loader information...
        Retrieving file information for '4787465'
        Parsing CurseForge pack download url
        Downloading https://edge.forgecdn.net/files/4787/465/All the Mods 8-1.0.28.zip
        Unpacking client manifest
Archive:  client.zip
  inflating: /mnt/server/manifest.json  
        Parsing client manifest
        Found loader forge 43.2.14 for Minecraft 1.19.2
Unpacking server files...
        Unpacking server.zip to /mnt/server
        Creating temporary directory
        Unpacking archive
        Setting glob settings
        Cleaning up directory structure
        Copying files to /mnt/server
Downloading Forge...
        Using Forge 1.19.2-43.2.14 from https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.14/forge-1.19.2-43.2.14
        Downloading Forge Installer 1.19.2-43.2.14 from https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.2.14/forge-1.19.2-43.2.14-installer.jar
        Installing Forge Server 1.19.2-43.2.14
/mnt/install/install.sh: line 292:   379 Killed                  java -jar forge-installer.jar --installServer > /dev/null 2>&1
        ERROR: Failed to install Forge Server 1.19.2-43.2.14

```

### Steps To Reproduce

Use this egg to install a Server.
Install
Hangs at said point.

### Install logs

https://pteropaste.com/pjt6xnzhe282/

**Comment by QuintenQVD0** [comment]
install logs faild because you do not have tail, it faild because you set unlimeted ram.

**Comment by Serph91P** [comment]
> install logs faild because you do not have tail, it faild because you set unlimeted ram.

generall isntall worked but now getting different error:

```
java @user_jvm_args.txt -Xms128M -Xmx8192M -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt
[10:35:50] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.16, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[10:35:50] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 18.0.2.1 by Eclipse Adoptium; OS Linux arch amd64 version 6.2.0-37-generic
[10:35:52] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[10:35:52] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/container/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[10:35:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/fmlcore/1.20.1-47.2.16/fmlcore-1.20.1-47.2.16.jar is missing mods.toml file
[10:35:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.2.16/javafmllanguage-1.20.1-47.2.16.jar is missing mods.toml file
[10:35:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.2.16/lowcodelanguage-1.20.1-47.2.16.jar is missing mods.toml file
[10:35:53] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/mclanguage/1.20.1-47.2.16/mclanguage-1.20.1-47.2.16.jar is missing mods.toml file
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: geckolib. Using Mod File: /home/container/mods/geckolib-forge-1.20.1-4.3.1.jar
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: botarium. Using Mod File: /home/container/mods/botarium-forge-1.20.1-2.2.1.jar
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: /home/container/mods/curios-forge-5.4.5+1.20.1.jar
[10:35:53] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: /home/container/mods/resourcefullib-forge-1.20.1-2.1.19.jar
[10:35:53] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 37 dependencies adding them to mods collection
[10:35:53] [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4,) wanted by AEAdditions-1.20.1-5.0.4.jar, found 3.11.0
[10:35:53] [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4.3,) wanted by InventoryProfilesNext-forge-1.20-1.10.9.jar, found 3.11.0
[10:35:53] [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [4.3,) wanted by libIPN-forge-1.20-4.0.1.jar, found 3.11.0
[10:35:53] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'minecraft', Requested by: 'xycraft_override', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'starlight', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'paucal', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'asynclocator', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'saturn', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'geckolib3', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'biggerreactors', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'phosphophyllite', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'nomowanderer', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'wirelesschargers', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'quartz', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'entangled', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'dummmmmmy', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'itemcollectors', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'integratednbt', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'tesseract', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'rsgauges', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'kotlinforforge', Requested by: 'sliceanddice', Expected range: '[4.3.0,)', Actual version: '3.11.0'
        Mod ID: 'minecraft', Requested by: 'ding', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'kotlinforforge', Expected range: '[1.18,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'adtetra', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'experiencebugfix', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'ae2', Requested by: 'appbot', Expected range: '[12.9.1,13.0.0)', Actual version: '15.0.15'
        Mod ID: 'minecraft', Requested by: 'tetranomicon', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'travelanchors', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'kotlinforforge', Requested by: 'flightlib', Expected range: '[4.3.0,)', Actual version: '3.11.0'
        Mod ID: 'minecraft', Requested by: 'xycraft_core', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'iceberg', Expected range: '[1.19,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'rootsclassic', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'xycraft_world', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'engineersdecor', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'getittogetherdrops', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'systeams', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'hexerei', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'aiotbotania', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'additionallanterns', Expected range: '[1.19,1.19.3)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'hexal', Expected range: '[1.19.2,1.19.2]', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'supermartijn642configlib', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'hexcasting', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'forge', Requested by: 'appbot', Expected range: '[43.0.0,44.0.0)', Actual version: '47.2.16'
        Mod ID: 'minecraft', Requested by: 'configured', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
        Mod ID: 'minecraft', Requested by: 'vitalize', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
[10:35:53] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
        Mod ID: 'appbot', Requested by: 'megacells', Expected range: '[1.5.0,)', Actual version: '1.4.5'
        Mod ID: 'theoneprobe', Requested by: 'ae2', Expected range: '[1.20.0,)', Actual version: '1.19-6.2.2'
Exception in thread "main" java.lang.module.ResolutionException: Modules geckolib3 and geckolib export package software.bernie.example.client.renderer.armor to module createaddition
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Comment by QuintenQVD0** [comment]
still no install logs

**Comment by Serph91P** [comment]
> still no install logs

got it fixed myself. Thanks for the help.
