### ISSUE TITLE
terraria egg

### ISSUE THREAD

**Issue by toonystank** [parkervcp/eggs#621]
on server
[Pterodactyl Daemon] No server egg configuration could be located; aborting startup.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] A fatal error was encountered while starting this server.

on daemon
14:11:47.605Z  WARN wings: Unable to determine size of server data folder, exited with code 1 signal null. (server=f57854d8-2fea-45e9-ab1c-3484011ee6b3)
    Error: Unable to determine size of server data folder, exited with code 1 signal null.
        at ChildProcess.<anonymous> (/srv/daemon/src/controllers/fs.js:89:29)
        at ChildProcess.emit (events.js:315:20)
        at ChildProcess.EventEmitter.emit (domain.js:482:12)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

**Comment by parkervcp** [comment]
This is identical to #620 and the reason I closed it is the same.
