### ISSUE TITLE
discord js egg won't install package.json

### ISSUE THREAD

**Issue by kasepta** [parkervcp/eggs#796]
```
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}
npm WARN Invalid version: "3.0"
npm WARN container No description
npm WARN container No repository field.
npm WARN container No README data
npm WARN container No license field.

up to date in 0.292s
found 0 vulnerabilities

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'module-alias/register'
Require stack:
- /home/container/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/index.js' ]
}
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.
```

**Comment by parkervcp** [comment]
Is this a public bot I can try for myself?

**Comment by Software-Noob** [comment]
> Is this a public bot I can try for myself?

He was in the Discord reporting this issue and said that it was a private bot hence could not replicate it

**Comment by parkervcp** [comment]
Well up until I have an example I can run I will close this. If I can get an example of this exact error we can re-open this issue.
