### ISSUE TITLE
Error start Discord bot Bastion v8.14.0

### ISSUE THREAD

**Issue by mrranger** [parkervcp/eggs#951]
Panel Version: (lastest)
Daemon Version: (lastest)
Service: (discord bot Bastion v8.14.0)
Modified: (no) (did you add or change things, this includes startup configs/install scripts/variables)

```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:bot_bastion 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ rmv() { echo -e stopping nodejs; for i in ; do kill ; done; echo -e stopping mongo; mongo --eval "db.getSiblingDB('admin').shutdownServer()" ; }; trap \'echo -e "ctrl-c caught" && rmv\'; mongod --fork --dbpath /home/container/mongodb/ --port 27017 --logpath /home/container/mongod.log && until nc -z -v -w5 127.0.0.1 27017; do echo 'Waiting for mongodb connection...'; sleep 5; done && yarn start
/entrypoint.sh: line 12: trap: -e: invalid signal specification
/entrypoint.sh: line 12: trap: ctrl-c caught: invalid signal specification
about to fork child process, waiting until server is ready for connections.
forked process: 18
child process started successfully, parent exiting
localhost [127.0.0.1] 27017 (?) open
yarn run v1.22.4
$ node .

Bastion v8.14.0
https://bastion.traction.one

</> with ❤ by The Bastion Bot Team & Contributors
Copyright © 2017-2020 The Bastion Bot Project

Thu Jan 28 2021 13:00:16 GMT+0300 (Moscow Standard Time) Shard 0 - Launching [ 1 of 1 ]
Thu Jan 28 2021 13:00:20 GMT+0300 (Moscow Standard Time) Shard 0 - Disconnected
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
[ERROR Thu Jan 28 2021 13:00:46 GMT+0300 (Moscow Standard Time)]
Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (/home/container/node_modules/discord.js/src/sharding/Shard.js:163:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  [Symbol(code)]: 'SHARDING_READY_TIMEOUT'
}
Trace
    at TesseractLogger.error (/home/container/node_modules/@bastion/tesseract/dist/TesseractLogger.js:1:3759)
[ERROR]
```

**Comment by Software-Noob** [comment]
That's not an issue with the egg, you need to allow privileged intents in your Discord developer portal for your bot.

**Comment by mrranger** [comment]
I checked everything, or what do you mean
https://prnt.sc/xr6qbn

**Comment by mrranger** [comment]
> That's not an issue with the egg, you need to allow privileged intents in your Discord developer portal for your bot.

Everything works, thank you!
